contact_links:
    - name: 📃 Documentation Issue
      url: https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}/issues/new
      about: This issue tracker is not for documentation issues. Please file documentation issues here.
    - name: 🤔 Questions and Help
      url: https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}/wiki
      about: This issue tracker is not for support questions. Please refer to the {{ cookiecutter.project_name }} wiki.